### ISSUE TITLE
Save?

### ISSUE THREAD

**Issue by Miladiir** [yyx990803/HTML5-Clear#4]
it isn't possible to save your tasks

you could sovle that with either a server site saving, which would mean many txt for you ;) or maybe a cookie for the client. that wouldn't last forever and also the client doesn't have to accept cookies.

another way of doing that is using mobilesafaris website-data-saving-feature thingie. don't remember its actual name, but you can look it up in Apples Developer Center

**Comment by Miladiir** [comment]
I just realized you did this to practice with HTML5 in relation to touchactions... silly me :) you most probably aren't interested in adding this feature :D

**Comment by yyx990803** [comment]
Thanks for the interest - it could be best done with HTML5 LocalStorage, but as you said I wasn't interested in adding that. Maybe in the future.
